name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  build:
    name: Package AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        jar cvf EmileALBERICI.war *
    - name: Copy file via SSH password
      uses: appleboy/scp-action@master
      with:
        host: ec2-13-37-215-179.eu-west-3.compute.amazonaws.com
        username: admin
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "EmileALBERICI.war"
        target: "/opt/tomcat/webapps"

  deploy:
    name: IPFS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: |
          jar cvf EmileALBERICI.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Save WAR file to IPFS
        run: |
          ls -la
          ipfs swarm peers
          ipfs add EmileALBERICI.war > cid.txt
          cp cid.txt $GITHUB_WORKSPACE/cid.txt
        shell: alpine.sh --root {0}

  download-cid:
    name: Download CID Artifact
    runs-on: windows-latest
    needs: deploy
    steps:
      - name: Download CID
        uses: actions/download-artifact@v2
        with:
          name: cid
          path: ${{ github.workspace }}

  save-cid-to-desktop:
    name: Save CID to Desktop
    runs-on: windows-latest
    needs: download-cid
    steps:
      - name: Move CID to Desktop
        run: |
          cp ${{ github.workspace }}/cid.txt $HOME\Desktop\cid.txt
        shell: PowerShell
