name: Industrialisation continue sur le serveur AWS (Tomcat)

on: push

jobs:
  build:
    name: Package AWS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Étape de récupération du code source depuis le référentiel Git

      - run: |
          jar cvf EmileALBERICI.war *
          # Créez un fichier WAR à partir du code source

  deploy:
    name: IPFS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      # Étape de récupération du code source depuis le référentiel Git

      - run: |
          jar cvf EmileALBERICI.war *
          # Créez un fichier WAR à partir du code source

      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
          # Installation d'Alpine Linux avec une version spécifique

      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
          # Installation d'IPFS et lancement du démon IPFS

      - name: Save WAR file to IPFS
        run: |
          ls -la
          ipfs swarm peers
          ipfs add EmileALBERICI.war > cid.txt
          # Génération du CID et sauvegarde dans le fichier cid.txt
        shell: alpine.sh --root {0}

# Les sections ci-dessous sont utilisées pour le transfert du fichier CID vers le bureau de l'utilisateur Windows.

  download-cid:
    name: Download CID Artifact
    runs-on: windows-latest
    needs: deploy

    steps:
      - name: Download CID
        uses: actions/download-artifact@v2
        with:
          name: cid
          path: ${{ github.workspace }}
          # Télécharge le fichier CID depuis l'artefact

  save-cid-to-desktop:
    name: Save CID to Desktop
    runs-on: windows-latest
    needs: download-cid

    steps:
      - name: Move CID to Desktop
        run: |
          cp ${{ github.workspace }}/cid.txt $HOME\Desktop\cid.txt
          # Copie le fichier CID vers le bureau de l'utilisateur
        shell: PowerShell
