name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  build:
    name: Package AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf EmileALBERICI.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ec2-13-37-215-179.eu-west-3.compute.amazonaws.com
        username: admin
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "EmileALBERICI.war"
        target: "/opt/tomcat/webapps"

  deploy:
    name: IPFS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf EmileALBERICI.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add EmileALBERICI.war > cid.txt
        shell: alpine.sh --root {0}
      
